import { MenuItem, AlBaladStory, Testimonial } from './types';

export const MENU_CATEGORIES = [
  { id: 'mutabbaq', name: 'المطبق الفريد', icon: 'Layers' },
  { id: 'fatair', name: 'الفطائر الزكية', icon: 'Egg' },
  { id: 'heritage', name: 'معصوب وعريكة', icon: 'Flame' },
  { id: 'platters', name: 'بلديات وشكاشيك', icon: 'Soup' },
  { id: 'meats', name: 'الكبدة واللحوم', icon: 'UtensilsCrossed' },
  { id: 'hot_drinks', name: 'استكانة الشاي', icon: 'Coffee' },
  { id: 'cold_drinks', name: 'العصائر الطبيعية', icon: 'Cherry' },
  { id: 'sides', name: 'الجانبيات والبطاطس', icon: 'Cookie' },
];

export const MENU_ITEMS: MenuItem[] = [
  // 1. المطبق
  {
    id: 'm1',
    name: 'مطبق خضار سادة',
    price: 8,
    category: 'mutabbaq',
    section: 'مطبق خضار',
    description: 'عجينة رقيقة ومقرمشة محشوة بالخضار الطازجة والكرات البلدي بنكهة تراثية ممتازة.',
    imageIcon: 'Layers',
    imageUrl: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&q=80&w=400',
    extras: [{ name: 'إضافة بيض', price: 2 }, { name: 'إضافة جبنة', price: 2 }],
  },
  {
    id: 'm2',
    name: 'مطبق خضار مع جبنة شيلي',
    price: 10,
    category: 'mutabbaq',
    section: 'مطبق خضار',
    description: 'مزيج المطبق التقليدي مع جبنة الشيلي الحارة لتجربة تلهب الحواس.',
    imageIcon: 'Flame',
    imageUrl: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&q=80&w=400',
    extras: [{ name: 'إضافة بيض', price: 2 }],
  },
  {
    id: 'm3',
    name: 'مطبق خضار مع جبنة سائلة',
    price: 10,
    category: 'mutabbaq',
    section: 'مطبق خضار',
    description: 'مطبق الخضار الغني مع مزيج الجبنة السائلة الفاخرة المنسكبة بلطف.',
    imageIcon: 'Combine',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=400',
    extras: [{ name: 'إضافة جبنة دبل', price: 2 }],
  },
  {
    id: 'm4',
    name: 'مطبق خضار مع جبنة مالحة',
    price: 10,
    category: 'mutabbaq',
    section: 'مطبق خضار',
    description: 'نكهة المطبق الكلاسيكية مع ملوحة الجبنة البيضاء التراثية العكاوي.',
    imageIcon: 'Grid',
    imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'm5',
    name: 'مطبق خضار دبل',
    price: 12,
    category: 'mutabbaq',
    section: 'مطبق خضار',
    description: 'حجم مضاعف من المطبق التقليدي المليء بالخضار اللذيذة والبيض الدبل.',
    imageIcon: 'Maximize',
    imageUrl: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'm6',
    name: 'مطبق الزمن الجميل',
    price: 12,
    category: 'mutabbaq',
    section: 'مطبق متنوع',
    description: 'خلطة سرية تعود بنا لأيام جدة القديمة وحكايات الفطور الأصيل بسوق الندى.',
    imageIcon: 'History',
    imageUrl: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&q=80&w=400',
    extras: [{ name: 'إضافة جبنة', price: 2 }],
  },
  {
    id: 'm7',
    name: 'مطبق البيضة المقشرة الخاص',
    price: 14,
    category: 'mutabbaq',
    section: 'مطبق متنوع',
    description: 'افضل مطبق في جدة! خلطة البيضة المقشرة الخاصة والغنية بأنواع الجبن الفاخرة والبيض البلدي.',
    imageIcon: 'Award',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'm8',
    name: 'مطبق تونة هانئ',
    price: 10,
    category: 'mutabbaq',
    section: 'مطبق متنوع',
    description: 'تونة بحرية ناعمة ومتبلة بالليمون والبهارات الحجازية داخل رقائق العجين المقرمش.',
    imageIcon: 'Fish',
    imageUrl: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'm9',
    name: 'مطبق حلو موز',
    price: 8,
    category: 'mutabbaq',
    section: 'مطبق حلو',
    description: 'التحلية الحجازية المفضلة! موز مهروس طازج ومحشوة في الرقاق ومحمر بالسمن البلدي.',
    imageIcon: 'Banana',
    imageUrl: 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'm10',
    name: 'مطبق حلو جبنة',
    price: 8,
    category: 'mutabbaq',
    section: 'مطبق حلو',
    description: 'مطبق حلو محشي بالجبن الدافئ وحليب محلى طعم ولا أروع.',
    imageIcon: 'CircleDot',
    imageUrl: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'm11',
    name: 'مطبق حلو مالح ومميز',
    price: 10,
    category: 'mutabbaq',
    section: 'مطبق حلو',
    description: 'التوازن المثالي بين المالح والحلو في لقمة واحدة تأخذك لزمن آخر.',
    imageIcon: 'Scale',
    imageUrl: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'm12',
    name: 'مطبق لبنة مع العسل',
    price: 10,
    category: 'mutabbaq',
    section: 'مطبق حلو',
    description: 'لبنة بلدية حامضة ولذيذة مغطاة بعسل السدر الصافي المعطر.',
    imageIcon: 'Droplet',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'm13',
    name: 'مطبق لبنة مع الزعتر',
    price: 10,
    category: 'mutabbaq',
    section: 'مطبق حلو',
    description: 'نكهات جبلية أصيلة تمزج حموضة اللبنة المترفة مع عطر الزعتر الجيري.',
    imageIcon: 'Sprout',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'm14',
    name: 'مطبق نوتيلا لغوص فريد',
    price: 12,
    category: 'mutabbaq',
    section: 'مطبق حلو',
    description: 'عشاق الشوكولاتة! رقائق الشوكولاتة البلجيكية الغنية موزعة بسخاء.',
    imageIcon: 'Cake',
    imageUrl: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=400',
  },

  // 2. الفطائر
  {
    id: 'f1',
    name: 'فطيرة سادة غبـش',
    price: 1.5,
    category: 'fatair',
    section: 'فطائر سادة وبيض',
    description: 'فطيرة الصبح السادة والمقرمشة مخبوزة على الطريقة الجداوية التقليدية.',
    imageIcon: 'Sun',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f2',
    name: 'فطيرة بيض مطهوة',
    price: 3,
    category: 'fatair',
    section: 'فطائر سادة وبيض',
    description: 'محشوة بالبيض المخفوق بالتوابل البلجيكية والعربية الكلاسيكية.',
    imageIcon: 'Egg',
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f3',
    name: 'فطيرة بيض دبل مستحقة',
    price: 4.5,
    category: 'fatair',
    section: 'فطائر سادة وبيض',
    description: 'بيض مزدوج مطبوخ بإتقان لتكون بداية يومك مليئة بالطاقة والقوة.',
    imageIcon: 'PlusCircle',
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f4',
    name: 'فطيرة أومليت بالمايونيز',
    price: 10,
    category: 'fatair',
    section: 'فطائر سادة وبيض',
    description: 'بيص أومليت ذهبي وشهي مع صوص الكريمة والمايونيز البارد.',
    imageIcon: 'Compass',
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f5',
    name: 'فطيرة أومليت بصلصة سيراتشا المايونيز',
    price: 10,
    category: 'fatair',
    section: 'فطائر سادة وبيض',
    description: 'ضربة حارة من صلصة سيراتشا التايلندية الأسطورية مدموجة بالمايونيز الغني.',
    imageIcon: 'FlameKindling',
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f6',
    name: 'فطيرة جبنة الصاج',
    price: 3,
    category: 'fatair',
    section: 'فطائر جبن',
    description: 'جبنة ذائبة مطاطية وشهية في قلب الفطيرة الساخنة.',
    imageIcon: 'ShieldAlert',
    imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f7',
    name: 'فطيرة جبنتين مدبّلة',
    price: 4.5,
    category: 'fatair',
    section: 'فطائر جبن',
    description: 'عشاق الملوحة والدسم الحجازي! ميكس فاخر من نوعين جبن ذائبة.',
    imageIcon: 'Shuffle',
    imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f8',
    name: 'فطيرة جبنة كلاسيك مع المربى',
    price: 4.5,
    category: 'fatair',
    section: 'فطائر جبن',
    description: 'أفضل ثنائية للفطور في ذاكرة السعوديين! جبنة بيضاء مالحة مع حلاوة مربى الفراولة.',
    imageIcon: 'Heart',
    imageUrl: 'https://images.unsplash.com/photo-1574085733277-851d9d856a3a?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f9',
    name: 'فطيرة جبنة وشيبس عمان عكاوي',
    price: 5,
    category: 'fatair',
    section: 'فطائر جبن',
    description: 'الفطيرة الأشهر للجمعات الشبابية! قرمشة شيبس عمان الكلاسيكي مع نعومة الجبنة.',
    imageIcon: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1574085733277-851d9d856a3a?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f10',
    name: 'فطيرة جبنة بالمربى وشيبسي عمان لغوصة',
    price: 6,
    category: 'fatair',
    section: 'فطائر جبن',
    description: 'مزيج المالح والحلو والمقرمش الحار! تجربة النخبة المطلقة بسوق الندى.',
    imageIcon: 'PartyPopper',
    imageUrl: 'https://images.unsplash.com/photo-1574085733277-851d9d856a3a?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f11',
    name: 'فطيرة البيضة المقشرة الذهبية (بيض، جبن، زيتون)',
    price: 6,
    category: 'fatair',
    section: 'فطائر أخرى',
    description: 'توليفة غنية من البيض المخفوق والجبنة الشيدر المعتقة وقطع الزيتون الفاخر.',
    imageIcon: 'Crown',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f12',
    name: 'فطيرة كبدة بلدي طازجة',
    price: 6,
    category: 'fatair',
    section: 'فطائر أخرى',
    description: 'كبدة غنم بلدي قلقلت بالبصل والطماطم والبهار، ومحشوة في فطيرة طازجة حامضة ومبخرة.',
    imageIcon: 'Beef',
    imageUrl: 'https://images.unsplash.com/photo-1628294895550-980a70c30b6d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f13',
    name: 'فطيرة لحم مقلقل',
    price: 6,
    category: 'fatair',
    section: 'فطائر أخرى',
    description: 'قطع اللحم الصغيرة المبهرة بالكمون والفلفل الحار والملفوفة بكتلة الفطير الشهية.',
    imageIcon: 'Drumstick',
    imageUrl: 'https://images.unsplash.com/photo-1628294895550-980a70c30b6d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'f14',
    name: 'ملوح صاج عملاق',
    price: 5,
    category: 'fatair',
    section: 'فطائر أخرى',
    description: 'عجينة الملوح التراثية الكبيرة، مخبوزة على الصاج الناري حتى تمام التحمير والقرمشة.',
    imageIcon: 'Disc',
    imageUrl: 'https://images.unsplash.com/photo-1470324161839-ce2bb6fa6bc3?auto=format&fit=crop&q=80&w=400',
  },

  // 3. معصوب وعريكة ومرسى وفتة
  {
    id: 'h1',
    name: 'معصوب ساده ع الحجر',
    price: 7,
    category: 'heritage',
    section: 'المعصوب التراثي',
    description: 'الموز المهروس مع خبز الصاج الطازج المقرمش برائحة البر الأصيل.',
    imageIcon: 'Activity',
    imageUrl: 'https://images.unsplash.com/photo-1541014741259-df5290db5785?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h2',
    name: 'معصوب بالقشطة الفاخرة',
    price: 10,
    category: 'heritage',
    section: 'المعصوب التراثي',
    description: 'معصوبنا البلدي مغطى بطبقة كثيفة ودسمة من القشطة الجداوية الصافية.',
    imageIcon: 'Cloud',
    imageUrl: 'https://images.unsplash.com/photo-1541014741259-df5290db5785?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h3',
    name: 'معصوب قشطة وعسل صافي',
    price: 12,
    category: 'heritage',
    section: 'المعصوب التراثي',
    description: 'تآلف النكهات الفاخرة! المعصوب مع الموز، القشطة الطازجة وقطرات عسل السدر الصافي.',
    imageIcon: 'Flower',
    imageUrl: 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h4',
    name: 'معصوب صاج بالكراميل',
    price: 12,
    category: 'heritage',
    section: 'المعصوب التراثي',
    description: 'يحمّر على الصاج الناري ليكتسب نكهة الكرملة والدهن البلدي الدافئ.',
    imageIcon: 'Flame',
    imageUrl: 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h5',
    name: 'معصوب البيضة المقشرة الإمبراطوري',
    price: 22,
    category: 'heritage',
    section: 'المعصوب التراثي',
    description: 'الصحن الأسطوري! قشطة، عسل، سمن بري، جبن شيدر مبشور، مكسرات محمصة وكورن فليكس مقرمش.',
    imageIcon: 'Gem',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h6',
    name: 'عريكة سادة دافئة',
    price: 7,
    category: 'heritage',
    section: 'العريكة الحجازية',
    description: 'البر الأسمر الفاخر معجون مع التمر والسمن البلدي الخالص.',
    imageIcon: 'Layers',
    imageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h7',
    name: 'عريكة تمر وقشطة دسمة',
    price: 10,
    category: 'heritage',
    section: 'العريكة الحجازية',
    description: 'العريكة التراثية بتناغم التمر الحجازي اللين مع كثافة القشطة الباردة.',
    imageIcon: 'Coins',
    imageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h8',
    name: 'عريكة قشطة جبن عسل ثنائية',
    price: 15,
    category: 'heritage',
    section: 'العريكة الحجازية',
    description: 'التوازن الفاخر بين ملوحة الجبنة الشيدر المبشورة وحلاوة العسل وسخاء القشطة البلدية.',
    imageIcon: 'HeartHandshake',
    imageUrl: 'https://images.unsplash.com/photo-1532499016263-f2c3e89df9cd?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h9',
    name: 'عريكة البيضة المقشرة الخاصة (الخلطة الذهبية)',
    price: 20,
    category: 'heritage',
    section: 'العريكة الحجازية',
    description: 'لغة العريكة بامتياز! قشطة، حليب مكثف محلى، جبن، سمن بلدي، كورن فليكس مقرمش، مكسرات وكاجو محمص.',
    imageIcon: 'Trophy',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1532499016263-f2c3e89df9cd?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h10',
    name: 'مرسى مشكل بالمن والسمن',
    price: 15,
    category: 'heritage',
    section: 'المرسى الجيزاني أصلي',
    description: 'من جنوبنا الحبيب! الدقيق الفاخر مخلوط بموز نضج ببطء مع السمن البري الدافئ والعسل الصافي والقشطة.',
    imageIcon: 'Compass',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436bb7050a4?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'h11',
    name: 'مغش فتة البيضة المقشرة الصخري',
    price: 25,
    category: 'heritage',
    section: 'الفتة وحكايا الطين',
    description: 'تقدم ساخنة تخرج غليانها في قدر الحجر الطبيعي (المغش) بنكهة السمسم العطرة وحليب مكثف ومكسرات وعسل وقشطة.',
    imageIcon: 'Castle',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=400',
  },

  // 4. الفول والفاصوليا والبازلاء والأطباق المتنوعة
  {
    id: 'p1',
    name: 'فول سادة مبخر ع الجمر',
    price: 15,
    category: 'platters',
    section: 'البلدي والمبخر',
    description: 'فول بلدي ناعم ومبخر بقطعة جمر مشتعلة، تنضح بزيت السمسم أو السمن البري الحافي.',
    imageIcon: 'Soup',
    imageUrl: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'p2',
    name: 'فاصوليا سادة بالبصل والطماطم',
    price: 15,
    category: 'platters',
    section: 'البلدي والمبخر',
    description: 'فاصوليا حمراء مطبوخة بالبصل المحروق، فص ثوم مفروم ولمسة بهار وجبنة بري.',
    imageIcon: 'UtilityPole',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'p3',
    name: 'بازلاء مطبوخة خضراء',
    price: 15,
    category: 'platters',
    section: 'البلدي والمبخر',
    description: 'بازلاء حلوة مهروسة بلطف ومبهّرة بالطريقة العدنية اللذيذة.',
    imageIcon: 'Shuffle',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'p4',
    name: 'مكس الوجهاء (فاصوليا وفول وبازلاء)',
    price: 15,
    category: 'platters',
    section: 'البلدي والمبخر',
    description: 'نصفين من الفول الحجازي والفاصوليا الحمراء يعلوهم البازلاء في توليفة فطور متكاملة.',
    imageIcon: 'Boxes',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'p5',
    name: 'شكشوكة عدني وافية حارقة',
    price: 15,
    category: 'platters',
    section: 'أطباق البيض الفريدة',
    description: 'البيض المخفوق بالطماطم المسبكة طويلاً والبصل المحروق والخلطة الحارة الشهية.',
    imageIcon: 'Dice',
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436bb7050a4?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'p6',
    name: 'بيض تركي مخفوق هادئ',
    price: 15,
    category: 'platters',
    section: 'أطباق البيض الفريدة',
    description: 'البيض المطبوخ على الطريقة الشرقية مع الزبدة ورقائق البابريكا وجبنة موزاريلا دافئة.',
    imageIcon: 'Moon',
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'p7',
    name: 'لحسة يمنية ريبال (بيض مع الجبنة السائلة)',
    price: 15,
    category: 'platters',
    section: 'أطباق البيض الفريدة',
    description: 'شكشوكة فاخرة مغطاة بطبقة غنية وساخنة من الجبنة الكاسات السائلة اللذيذة.',
    imageIcon: 'Paintbrush',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&q=80&w=400',
  },

  // 5. الكبدة واللحوم
  {
    id: 'v1',
    name: 'كبدة بلدي طازجة بالبصل والبهار',
    price: 20,
    category: 'meats',
    section: 'لحوم بلدي طازجة',
    description: 'كبدة خروف بلدي طازية تقطع وتحمر بالبصل، الفليفلة، طماطم، وبهارات عم بكر السرية.',
    imageIcon: 'Beef',
    imageUrl: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&q=80&w=400',
    extras: [{ name: 'إضافة جبنة شيلي', price: 2 }],
  },
  {
    id: 'v2',
    name: 'لحم مقلقل بلدي مندي',
    price: 20,
    category: 'meats',
    section: 'لحوم بلدي طازجة',
    description: 'شقف اللحم البلدي الطري المحمرة بالسمن الطبيعي، الكزبرة، الزعفران وفلفل أخضر حار.',
    imageIcon: 'Flame',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'v3',
    name: 'لحم مفروم طازج بالبيض والكرات',
    price: 20,
    category: 'meats',
    section: 'لحوم بلدي طازجة',
    description: 'اللحم المفروم الطازج المعصج مع البهارات العربية والكرات الجداوي المنعش.',
    imageIcon: 'Grid',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'v4',
    name: 'عقدة دجاج تهاميه',
    price: 15,
    category: 'meats',
    section: 'العقد البلدي',
    description: 'شقف الدجاج المطهوة على نار هادئة بالمرق المبخر والثوم ونكهات الجبل.',
    imageIcon: 'ChefHat',
    imageUrl: 'https://images.unsplash.com/photo-1534080391025-a77af6be35e5?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'v5',
    name: 'عقدة جمبري ملوكية',
    price: 20,
    category: 'meats',
    section: 'العقد البلدي',
    description: 'جمبري البحر الأحمر الطازج، مطبوخ في الفخار مع الصوص الحجازي الأحمر الكثيف والكزبرة.',
    imageIcon: 'Compass',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=400',
  },

  // 6. المشروبات الساخنة
  {
    id: 'd1',
    name: 'استكانة شاي جمر أصلي',
    price: 5,
    category: 'hot_drinks',
    section: 'شاهي بالكوب',
    description: 'الشاهي السيلاني الفاخر المطبوخ ببطء شديد على الفحم الحار ليكتسب الطعم المعتق.',
    imageIcon: 'Flame',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'd2',
    name: 'استكانة شاي كرك بالهيل والزعفران',
    price: 5,
    category: 'hot_drinks',
    section: 'شاهي بالكوب',
    description: 'شاي ثقيل مع حليب بوني المطبوخ، الهيل الأصيل وخيوط الزعفران الإيراني الفاخر.',
    imageIcon: 'Zap',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'd3',
    name: 'شاهي عدني أصيل بالحليب',
    price: 1.5,
    category: 'hot_drinks',
    section: 'شاهي بالكوب',
    description: 'الشاي العدني التقليدي بسعر رمزي ورايق يناسب صباحات البلد المزدحمة.',
    imageIcon: 'Clock',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'd4',
    name: 'شاي عدني مفور ومكثف',
    price: 3,
    category: 'hot_drinks',
    section: 'شاهي بالكوب',
    description: 'شاي عدني يفّور على النار الكبيرة مع أعواد القرفة والقرنفل الساحر.',
    imageIcon: 'TrendingUp',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'd5',
    name: 'ترمس شاي كرك العائلة (1 لتر)',
    price: 35,
    category: 'hot_drinks',
    section: 'الترامس والجمعات',
    description: 'أفضل رفيق لجمعات الأصدقاء والعوائل في ساحات جدة البلد! ترمس أنيق محتفظ بحرارته.',
    imageIcon: 'Container',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'd6',
    name: 'دلة قهوة سعودية ملكية مع التمر المقشر',
    price: 25,
    category: 'hot_drinks',
    section: 'القهوة والبن',
    description: 'البن الهرري الفاخر المحمص شقراء، المبهّر بالهيل النظيف العطري والمسمار، تقدم مع سكري فاخر دافئ.',
    imageIcon: 'Coffee',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=400',
  },

  // 7. العصائر الفاخرة والخلطات
  {
    id: 'c1',
    name: 'عصير برتقال طازج منعش',
    price: 8,
    category: 'cold_drinks',
    section: 'العصائر الكلاسيكية',
    description: 'ثمرة البرتقال الحجازي الباردة، معصورة فورًا لتروي العطش في ظهيرات البلد المفتوحة.',
    imageIcon: 'Activity',
    imageUrl: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'c2',
    name: 'عصير عوار قلب أسطوري',
    price: 12,
    category: 'cold_drinks',
    section: 'العصائر الكلاسيكية',
    description: 'المزيج التاريخي الأشهر للفراولة والمانجو مع الآيس كريم الفانيليا المخملي.',
    imageIcon: 'Heart',
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'c3',
    name: 'أفوكادو ياقوت ملكي بالمكسرات',
    price: 13,
    category: 'cold_drinks',
    section: 'خلطات الأفوكادو الخاصة',
    description: 'عصير الأفوكادو الكثيف الغني بالبروتينات يعلوه عسل السدر الصافي وجوز عين الجمل واللوز المحمص الفاخر.',
    imageIcon: 'Gem',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'c4',
    name: 'عصير بربر الأسطوري الملكي الحارثي',
    price: 15,
    category: 'cold_drinks',
    section: 'عصائر صحية وتراثية',
    description: 'مزيج الحليب البلدي الطازج، الموز العضوي مع رطب المدينة وعسل برّي ولمسة حلبة تمنحك طاقة لا تنضب.',
    imageIcon: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=400',
  },

  // 8. الأصناف الجانبية والبطاطس
  {
    id: 's1',
    name: 'سحاوق جبن فاخر يمني',
    price: 5,
    category: 'sides',
    section: 'المقبلات والجانبيات',
    description: 'مبشور الجبنة مع الطماطم والكزبرة، الثوم والفلفل الحار المهروس في الهاون الحجري المتميز.',
    imageIcon: 'Utensils',
    imageUrl: 'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 's2',
    name: 'بطاطس جيزاني ذهبي',
    price: 5,
    category: 'sides',
    section: 'المقبلات والجانبيات',
    description: 'البطاطس المحلية المقلية بالطريقة التقليدية مع رشّة بهار البابريكا والكمون.',
    imageIcon: 'Grid',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 's3',
    name: 'بطاطس مدفون بالدخان',
    price: 10,
    category: 'sides',
    section: 'المقبلات والجانبيات',
    description: 'حبات البطاطس المشوية تحت رمال الفحم الحار بنكهة الطين والدخان الساحرة، مع صوص الثومية الخاص بنا.',
    imageIcon: 'Flame',
    accentColor: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&q=80&w=400',
  }
];

export const ALBALAD_STORIES: AlBaladStory[] = [
  {
    id: 'story1',
    title: 'سوق الندى.. منبع العراقة التاريخية',
    text: 'تأسس سوق الندى منذ ما يزيد عن 150 عاماً في قلب حارتنا بجدة التاريخية، وكان محطة القوافل والحجاج القادمين عبر بحر الأحمر لشراء أفضل الخبز، الحبوب، والمطبق التراثي اللذيذ من أجدادنا الأقدمون.',
    imageDescription: 'سوق تراثي تقليدي يضج بالباعة والدكاكين والبيوت الطينية الحجازية الراقية',
    iconName: 'History',
  },
  {
    id: 'story2',
    title: 'سر اسم البيضة المقشرة',
    text: 'في حارات البلد القديمة، كان يُضرب المثل بالشيء الأبيض الناصع والنظيف والخالي من العيوب بـ "البيضة المقشرة". اخترنا هذا الاسم لأن فطورنا ناصع البياض ببركة المكونات الطازجة والنظافة التي لا تفارق دكاننا.',
    imageDescription: 'دكان حجازي تراثي بباب خشبي عتيق مزخرف وفانوس يتدلى من السقف',
    iconName: 'Sparkles',
  },
  {
    id: 'story3',
    title: 'شارع شحاتة.. ذاكرة الروشان والناس',
    text: 'عشنا في شارع شحاتة وكبرنا بين رواشينه العتيقة الخشبية المظللة التي تحكي حكاوي العائلات الحجازية الكريمة، واليوم نستقبلكم بذات الجود والترحيب والصفاء في ذات الزقاق.',
    imageDescription: 'نوافذ خشبية تقليدية مزخرفة تنعكس عليها الرمال وأشعة الشمس الذهبية',
    iconName: 'Home',
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    name: 'أبو فهد العصيمي',
    role: 'من سكان حارة المظلوم القدامى',
    text: 'ما شاء الله تبارك الله، عريكة البيضة المقشرة هذي فيها طعم السمن الحقيقي والبر الأصلي اللي يذكرني بطبخ جدتي الله يرحمها. الفطور عندهم يفتح النفس والعم بكر يستقبلك بوجه بشوش ينسيك هموم اليوم.',
    avatar: '👨‍🦳',
    rating: 5,
    date: 'منذ يومين',
  },
  {
    name: 'فاطمة الأحمدي',
    role: 'زائرة ومتذوقة سياحية',
    text: 'المكان ممتع بصرياً ومبهر! المطبق الساخن مع شاي الكرك بالزعفران هيل غني جداً. تصميم المطعم التراثي والأنغام الحجازية تمنحك شعوراً بأنك تسافر عبر الزمن في وسط جدة التاريخية. ضروري تزوروه!',
    avatar: '👩‍💼',
    rating: 5,
    date: 'منذ أسبوع',
  },
  {
    name: 'محمد باخشوين',
    role: 'ناقد طعام ومحب للبلد',
    text: 'لوحة مطبق البيضة المقشرة هي الأفضل بدون منافس ومغش الفتة الحجري رهيب وساخن لدرجة الإدمان. النظافة رائعة والأسعار في متناول الجميع مقارنة بالجودة الكبيرة.',
    avatar: '👨‍🍳',
    rating: 5,
    date: 'منذ ٣ أيام',
  }
];
